services:
  etcd:
    image: quay.io/coreos/etcd:v3.4.13
    container_name: etcd
    restart: unless-stopped
    environment:
      - ETCD_NAME=${NODE_NAME} # Change this to node2 on the second machine
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://${NODE_IP_ADDRESS}:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://${NODE_IP_ADDRESS}:2379
      - ETCD_INITIAL_CLUSTER=etcd-node-01=http://${NODE_01_IP_ADDRESS}:2380,etcd-node-02=http://${NODE_02_IP_ADDRESS}:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-01
      - ETCD_INITIAL_CLUSTER_STATE=new
    ports:
      - "2379:2379"
      - "2380:2380"