services:
  leantime_db:
    image: mysql:8.0
    container_name: leantime-mysql
    volumes:
      - /opt/docker/volumes/leantime/mysql:/var/lib/mysql
    restart: unless-stopped
    env_file: ./.env
    command: --character-set-server=UTF8MB4 --collation-server=UTF8MB4_unicode_ci

  leantime:
    image: leantime/leantime:latest
    container_name: leantime
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - /opt/docker/volumes/leantime/public_data:/var/www/html/public/userfiles
      - /opt/docker/volumes/leantime/data:/var/www/html/userfiles
    ports:
      - "8080:80"                                                       # The port to expose and access Leantime
    depends_on:
      - leantime_db                                                     # Don't start Leantime unless leantime_db is running