services:
  gatus:
    container_name: gatus
    image: twinproduction/gatus:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /opt/docker/volumes/gatus/config.yaml:/config/config.yaml
      - /opt/docker/volumes/gatus/db:/db