services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: stirlingpdf
    restart: unless-stopped
    mem_limit: 1g
    memswap_limit: 1g
    mem_reservation: 512m
    cpus: 2
    ports:
      - '80:8080'
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=hu_HU
    volumes:
      - /opt/docker/volumes/stirlingpdf/trainingData:/usr/share/tessdata #Required for extra OCR languages
      - /opt/docker/volumes/stirlingpdf/extraConfigs:/configs
#      - ./customFiles:/customFiles/
#      - ./logs:/logs/