services:
  it-tools:
    image: corentinth/it-tools
    container_name: it-tools
    hostname: it-tools
    restart: unless-stopped
    mem_limit: 512m
    memswap_limit: 512m
    mem_reservation: 256m
    cpus: 2
    ports:
      - 80:80/tcp