services:
  gravity:
    # Important for this to be static and unique
    hostname: gravity-dns-01
    image: ghcr.io/beryju/gravity:stable
    restart: unless-stopped
    # network_mode: host
    ports:
      - "53:53/udp" #DNS service
      - "53:53/tcp" #DNS service
      - 80:8008
      # - 8009
      # - 2379
      # - 2380
      # - 8100
    volumes:
      - /opt/docker/volumes/gravity/data:/data
    # environment:
    #   LOG_LEVEL: info
    # The default log level of info logs DHCP and DNS queries, so ensure
    # the logs aren't filling up the disk
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"