services:
  netbootxyz:
    image: linuxserver/netbootxyz:latest
    container_name: netbootxyz
    restart: unless-stopped
    mem_limit: 1024m
    memswap_limit: 1024m
    mem_reservation: 512M
    cpus: 1
    # dns:
    #   - 100.100.100.100
    #   - 1.1.1.1
    environment:
      - PUID=4000
      - GUID=4000
      - TZ=Europe/Budapest
      - PORT_RANGE=30000:30010 #optional
      - SUBFOLDER=/ #optional
      # - TAILSCALE_AUTHKEY=${TS_AUTHKEY}
      # - TAILSCALE_EXTRA_ARGS=--advertise-tags=tag:container
      # - TAILSCALE_USE_SSH=0
      # - TAILSCALE_STATE_DIR=/var/lib/tailscale
      # - TAILSCALE_SERVE_PORT=3000
      # - TAILSCALE_SERVE_MODE=https
      # - TAILSCALE_HOSTNAME=${CT_HOSTNAME}
      # - DOCKER_MODS=ghcr.io/tailscale-dev/docker-mod:main
    volumes:
      - /opt/docker/volumes/netbootxyz/config:/config
      - /assets:/assets #optional
      # - /opt/docker/volumes/netbootxyz/state:/var/lib/tailscale
    ports:
      - 69:69/udp
      - 100.64.1.13:80:3000 #optional
      - 8080:80 #optional
