services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    restart: unless-stopped
    mem_limit: 512m
    memswap_limit: 512m
    mem_reservation: 256m
    cpus: 1
    dns:
      - 100.100.100.100
    networks:
      stack_network:
        ipv4_address: 10.0.0.2
    environment:
      - PUID=4000
      - PGID=4000
      - TZ=Europe/Budapest
      - APP_URL=https://${DOMAIN}
      - DB_HOST=10.0.0.3
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=${DATABASE_PASSWORD}
      - DB_DATABASE=bookstackapp
    volumes:
      - /opt/docker/volumes/bookstack/config:/config
    ports:
      - ${BIND_ADDRESS:-127.0.0.1}:8080:80/tcp
    security_opt:
      - no-new-privileges:true
    depends_on:
      - bookstack_db
    healthcheck:
      test: ["CMD-SHELL", "wget --spider 127.0.0.1:80"]
      interval: 10s
      timeout: 5s
      retries: 60

  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    restart: unless-stopped
    mem_limit: 512m
    memswap_limit: 512m
    mem_reservation: 256m
    cpus: 1
    dns:
      - 100.100.100.100
    security_opt:
      - no-new-privileges:true    
    networks:
      stack_network:
        ipv4_address: 10.0.0.3
    environment:
      - PUID=4000
      - PGID=4000
      - TZ=Europe/London
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - /opt/docker/volumes/bookstack/mariadb:/config

networks:
  stack_network:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24