  services:
    traefik:
      image: traefik:latest
      container_name: traefik
      restart: unless-stopped
      mem_limit: 384m
      memswap_limit: 384m
      mem_reservation: 128m
      cpus: 2
      network_mode: host
      dns:
        # - 1.1.1.1
        - 100.100.100.100
      # dns_search:
      #   - tail0e99d.ts.net
      security_opt:
        - no-new-privileges:true
      environment:
        - CLOUDFLARE_POLLING_INTERVAL=10
        - CLOUDFLARE_PROPAGATION_TIMEOUT=100
        - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
        # If you choose to use an API Key instead of a Token, specify your email as well
        #- CF_API_EMAIL=${CF_API_EMAIL}        
        #- CF_API_KEY=${CF_API_KEY}
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /opt/docker/volumes/traefik/data/traefik.yml:/traefik.yml:ro
        - /opt/docker/volumes/traefik/data/acme.json:/acme.json
        - /opt/docker/volumes/traefik/data/config.yml:/config.yml:ro
        - /opt/docker/volumes/traefik/data/logs:/logs
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.entrypoints=http"
        - "traefik.http.routers.traefik.rule=Host(`${DASHBOARD_SUBDOMAIN}.${DOMAIN}`)"
        - "traefik.http.middlewares.traefik-auth.basicauth.users=${BASIC_AUTH}"
        - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
        - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
        - "traefik.http.routers.traefik-secure.entrypoints=https"
        - "traefik.http.routers.traefik-secure.rule=Host(`${DASHBOARD_SUBDOMAIN}.${DOMAIN}`)"
        - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
        - "traefik.http.routers.traefik-secure.tls=true"
        - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
        - "traefik.http.routers.traefik-secure.tls.domains[0].main=${DOMAIN}"
        - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.${DOMAIN}"
        - "traefik.http.routers.traefik-secure.service=api@internal"
    
    nginx:
      image: nginx:alpine
      ports:
        - 100.80.100.102:8080:80
      volumes:
        - /opt/docker/volumes/goaccess/report:/usr/share/nginx/html:ro 
      depends_on:
        - goaccess
      labels:
      - traefik.enable=true
      - app.name=go

    goaccess:
      image: allinurl/goaccess
      restart: always
      command: > 
        /srv/logs/access.log
        -o /srv/report/index.html
        --real-time-html
        --origin=https://stats.lab.escapethelan.com
        --ws-url=wss://stats.lab.escapethelan.com:443/live
        --log-format='%h %^[%d:%t %^] "%r" %s %b %R %u %^ %v %^ %Lms'
        --time-format='%H:%M:%S'
        --date-format='%d/%b/%Y'
        --db-path=/srv/data
        --persist
        --restore
      ports:
        - 100.80.100.102:7890:7890
      volumes:
      # - data:/srv/logs:ro
      # - web:/srv/report
      # - goaccess_data:/srv/data
      - /opt/docker/volumes/traefik/data/logs:/srv/logs:ro
      - /opt/docker/volumes/goaccess/report:/srv/report
      - /opt/docker/volumes/goaccess/data:/srv/data