services:
  gotify:
    image: gotify/server
    container_name: gotify
    restart: unless-stopped
    mem_limit: 256m
    memswap_limit: 256m
    mem_reservation: 128m
    cpus: 2
    ports:
      - 80:80/tcp
    environment:
      - TZ=Europe/Budapest
    volumes:
      - /opt/docker/volumes/gotify/conf:/etc/gotify
      - /opt/docker/volumes/gotify/appdata/data:/app/data
    cap_drop:
      - all
    cap_add:
      - net_bind_service
    security_opt:
      - no-new-privileges


      curl "https://gotify.lab.escapethelan.com/message?token=AA74mNrUiyNeAv0" -F "title=my title" -F "message=my message" -F "priority=5"