# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    network_mode: service:tailscale
    mem_limit: 512m
    memswap_limit: 512m
    mem_reservation: 384m
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    environment:
      TZ: 'Europe/Budapest'
      WEBPASSWORD: '${WEB_PASSWORD}'
    # Volumes store your data between container upgrades
    volumes:
      - '/opt/docker/volumes/pihole/etc-pihole:/etc/pihole'
      - '/opt/docker/volumes/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    security_opt:
      - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "ss -nputwl | grep LISTEN | grep 80"]
      interval: 10s
      timeout: 5s
      retries: 60
    depends_on:
      tailscale:
        condition: service_healthy
  tailscale:
    image: tailscale/tailscale:latest
    hostname: ${CT_HOSTNAME}
    restart: unless-stopped
    mem_limit: 128m
    memswap_limit: 128m
    mem_reservation: 64m
    cpus: 1
    expose:
       - 53/tcp
       - 53/udp
       - 80/tcp
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container --accept-dns=false --stateful-filtering=false
      - TS_SERVE_CONFIG=/config/tailscale.json
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - "/opt/docker/volumes/pihole/tailscale/state:/var/lib/tailscale"
      - "/opt/docker/stacks/pihole/tailscale.json:/config/tailscale.json:ro"
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - net_admin
      - sys_module
      - net_raw    
    security_opt:
      - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "tailscale status"]
      interval: 10s
      timeout: 5s
      retries: 60