http:
 #region routers 
  routers:
    lxc-searxng:
      entryPoints:
        - "https"
      rule: "Host(`searxng.lab.escapethelan.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: lxc-searxng
    netbootxyz:
      entryPoints:
        - "https"
      rule: "Host(`netbootxyz.lab.escapethelan.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: netbootxyz
    paperlessngx:
      entryPoints:
        - "https"
      rule: "Host(`paperless.lab.escapethelan.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: paperlessngx
    linkwarden:
      entryPoints:
        - "https"
      rule: "Host(`linkwarden.lab.escapethelan.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: linkwarden
    
    lxc-technitium-01:
      entryPoints:
        - "https"
      rule: "Host(`tcdns01.lab.escapethelan.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: lxc-technitium-01
    lxc-technitium-02:
      entryPoints:
        - "https"
      rule: "Host(`tcdns02.lab.escapethelan.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: lxc-technitium-02
    adguardhome-01:
      entryPoints:
        - "https"
      rule: "Host(`aghdns01.lab.escapethelan.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: adguardhome-01
    adguardhome-02:
      entryPoints:
        - "https"
      rule: "Host(`aghdns02.lab.escapethelan.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: adguardhome-02


#endregion
#region services
  services:
    lxc-searxng:
      weighted:
        healthCheck: {}
        services:
        - name: lxc-searxng-01
          weight: 1
        - name: lxc-searxng-02
          weight: 2

    lxc-searxng-01:
      loadBalancer:
        healthCheck:
          path: /stats
          interval: 10s
          timeout: 3s
        servers:
        - url: "http://100.64.10.1"

    lxc-searxng-02:
      loadBalancer:
        healthCheck:
          path: /stats
          interval: 10s
          timeout: 3s
        servers:
        - url: "http://100.64.10.2"

    netbootxyz:
      loadBalancer:
        servers:
          - url: "http://100.64.1.13:3000"
        passHostHeader: true

    paperlessngx:
      loadBalancer:
        servers:
          - url: "http://100.64.10.3:8000"
        passHostHeader: true

    linkwarden:
      loadBalancer:
        servers:
          - url: "http://100.64.10.4:3000"
        passHostHeader: true
    
    lxc-technitium-01:
      loadBalancer:
        servers:
          - url: "http://100.64.100.101:5380"
        passHostHeader: true
    
    lxc-technitium-02:
      loadBalancer:
        servers:
          - url: "http://100.64.100.102:5380"
        passHostHeader: true

    adguardhome-01:
      loadBalancer:
        servers:
          - url: "http://100.64.100.201"
        passHostHeader: true
    
    adguardhome-02:
      loadBalancer:
        servers:
          - url: "http://100.64.100.202"
        passHostHeader: true

#endregion
  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true

    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    default-whitelist:
      ipWhiteList:
        sourceRange:
        - "10.0.0.0/8"
        - "192.168.0.0/16"
        - "172.16.0.0/12"
        - "100.64.0.0/10"

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers