http:
 #region routers 
  routers:
    vm-searxng:
      entryPoints:
        - "https"
      rule: "Host(`searxng.lab.escapethelan.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: vm-searxng
    netbootxyz:
      entryPoints:
        - "https"
      rule: "Host(`netbootxyz.lab.escapethelan.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: netbootxyz

#endregion
#region services
  services:
    vm-searxng:
      weighted:
        healthCheck: {}
        services:
        - name: vm-searxng-01
          weight: 1
        - name: vm-searxng-02
          weight: 2

    vm-searxng-01:
      loadBalancer:
        healthCheck:
          path: /stats
          interval: 10s
          timeout: 3s
        servers:
        - url: "http://100.64.10.1"

    vm-searxng-02:
      loadBalancer:
        healthCheck:
          path: /stats
          interval: 10s
          timeout: 3s
        servers:
        - url: "http://100.64.10.2"

    netbootxyz:
      loadBalancer:
        servers:
          - url: "https://100.64.10.177:443"
        passHostHeader: true


#endregion
  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true

    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    default-whitelist:
      ipWhiteList:
        sourceRange:
        - "10.0.0.0/8"
        - "192.168.0.0/16"
        - "172.16.0.0/12"
        - "100.64.0.0/10"

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers