http:
 #region routers 
  routers:
    lxc-searxng:
      entryPoints:
        - "https"
      rule: "Host(`searxng.lab.escapethelan.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: lxc-searxng
    lxc-gotify:
      entryPoints:
        - "https"
      rule: "Host(`gotify.lab.escapethelan.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: lxc-gotify
    lxc-netbootxyz:
      entryPoints:
        - "https"
      rule: "Host(`netbootxyz.lab.escapethelan.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: lxc-netbootxyz
    lxc-paperlessngx:
      entryPoints:
        - "https"
      rule: "Host(`paperless.lab.escapethelan.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: lxc-paperlessngx
    lxc-uptimekuma:
      entryPoints:
        - "https"
      rule: "Host(`uptimekuma.lab.escapethelan.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: lxc-uptimekuma
    lxc-linkwarden:
      entryPoints:
        - "https"
      rule: "Host(`linkwarden.lab.escapethelan.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: lxc-linkwarden
    lxc-bookstack:
      entryPoints:
        - "https"
      rule: "Host(`bookstack.lab.escapethelan.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: lxc-bookstack
    lxc-it-tools:
      entryPoints:
        - "https"
      rule: "Host(`ittools.lab.escapethelan.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: lxc-it-tools
    lxc-web-check:
      entryPoints:
        - "https"
      rule: "Host(`webcheck.lab.escapethelan.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: lxc-web-check
    lxc-speedtest:
      entryPoints:
        - "https"
      rule: "Host(`speedtest.lab.escapethelan.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: lxc-speedtest
    lxc-stirlingpdf:
      entryPoints:
        - "https"
      rule: "Host(`stirlingpdf.lab.escapethelan.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: lxc-stirlingpdf
    lxc-technitium-01:
      entryPoints:
        - "https"
      rule: "Host(`tcdns01.lab.escapethelan.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: lxc-technitium-01
    lxc-technitium-02:
      entryPoints:
        - "https"
      rule: "Host(`tcdns02.lab.escapethelan.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: lxc-technitium-02
    lxc-technitium-03:
      entryPoints:
        - "https"
      rule: "Host(`tcdns03.lab.escapethelan.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: lxc-technitium-03
    adguardhome-01:
      entryPoints:
        - "https"
      rule: "Host(`aghdns01.lab.escapethelan.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: adguardhome-01
    adguardhome-02:
      entryPoints:
        - "https"
      rule: "Host(`aghdns02.lab.escapethelan.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: adguardhome-02
    adguardhome-03:
      entryPoints:
        - "https"
      rule: "Host(`aghdns03.lab.escapethelan.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: adguardhome-03

#endregion
#region services
  services:
    lxc-searxng:
      weighted:
        healthCheck: {}
        services:
        - name: lxc-searxng-01
          weight: 2
        - name: lxc-searxng-02
          weight: 1
        - name: lxc-searxng-03
          weight: 3

    lxc-searxng-01:
      loadBalancer:
        healthCheck:
          path: /stats
          interval: 10s
          timeout: 3s
        servers:
        - url: "http://lxc-searxng-01"

    lxc-searxng-02:
      loadBalancer:
        healthCheck:
          path: /stats
          interval: 10s
          timeout: 3s
        servers:
        - url: "http://lxc-searxng-02"

    lxc-searxng-03:
      loadBalancer:
        healthCheck:
          path: /stats
          interval: 10s
          timeout: 3s
        servers:
        - url: "http://lxc-searxng-03"

    lxc-linkwarden:
      loadBalancer:
        servers:
          - url: "http://lxc-linkwarden"
        passHostHeader: true

    lxc-bookstack:
      loadBalancer:
        servers:
          - url: "http://lxc-bookstack"
        passHostHeader: true

    lxc-it-tools:
      loadBalancer:
        servers:
          - url: "http://lxc-it-tools"
        passHostHeader: true

    lxc-paperlessngx:
      loadBalancer:
        servers:
          - url: "http://lxc-paperless-ngx"
        passHostHeader: true

    lxc-uptimekuma:
      loadBalancer:
        servers:
          - url: "http://lxc-uptimekuma"
        passHostHeader: true

    lxc-web-check:
      loadBalancer:
        servers:
          - url: "http://lxc-web-check"
        passHostHeader: true

    lxc-speedtest:
      loadBalancer:
        servers:
          - url: "http://lxc-speedtest"
        passHostHeader: true

    lxc-stirlingpdf:
      loadBalancer:
        servers:
          - url: "http://lxc-stirlingpdf"
        passHostHeader: true

    lxc-netbootxyz:
      loadBalancer:
        servers:
          - url: "http://lxc-netbootxyz"
        passHostHeader: true

    lxc-gotify:
      loadBalancer:
        servers:
          - url: "http://lxc-gotify"
        passHostHeader: true
    
    lxc-technitium-01:
      loadBalancer:
        servers:
          - url: "http://lxc-technitium-01:5380"
        passHostHeader: true
    
    lxc-technitium-02:
      loadBalancer:
        servers:
          - url: "http://lxc-technitium-02:5380"
        passHostHeader: true
    
    lxc-technitium-03:
      loadBalancer:
        servers:
          - url: "http://lxc-technitium-03:5380"
        passHostHeader: true

    adguardhome-01:
      loadBalancer:
        servers:
          - url: "http://agh-dns-01"
        passHostHeader: true
    
    adguardhome-02:
      loadBalancer:
        servers:
          - url: "http://agh-dns-02"
        passHostHeader: true
    
    adguardhome-03:
      loadBalancer:
        servers:
          - url: "http://agh-dns-03"
        passHostHeader: true
    

#endregion
  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true

    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    default-whitelist:
      ipWhiteList:
        sourceRange:
        - "10.0.0.0/8"
        - "192.168.0.0/16"
        - "172.16.0.0/12"
        - "100.64.0.0/10"

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers