version: "3.8"
services:
  linkding:
    image: docker.io/sissbruecker/linkding:latest
    container_name: linkding
    restart: unless-stopped
    user: 4000:4000
    mem_limit: 256m
    memswap_limit: 256m
    mem_reservation: 128m
    cpus: 1
    ports:
      - 8080:9090
    environment:
      - TZ=Europe/Budapest
      # - LD_CSRF_TRUSTED_ORIGINS=https://${CT_HOSTNAME}.tail0e99d.ts.net
    volumes:
      - /opt/podman/volumes/linkding/appdata:/etc/linkding/data
    cap_drop:
      - all
    cap_add:
      - chown
      - setuid
      - setgid
      - net_bind_service
    security_opt:
      - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:9090"]
      interval: 10s
      timeout: 5s
      retries: 60