services:
  fusion:
    image: rook1e404/fusion
    hostname: fusion
    container_name: fusion
    restart: unless-stopped
    mem_limit: 512m
    memswap_limit: 512m
    mem_reservation: 256m
    cpus: 1
    user: 4000:4000
    dns:
      - 100.100.100.100
    cap_drop:
      - all
    security_opt:
      - no-new-privileges:true
    ports:
      - ${BIND_ADDRESS:-127.0.0.1}:8080:8080/tcp
    volumes:
      - /opt/docker/volumes/fusion/data:/data
    environment:
      - PASSWORD=${PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "wget --spider 127.0.0.1:8080"]
      interval: 10s
      timeout: 5s
      retries: 60