services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    network_mode: service:tailscale
    # user: 4000:4000
    mem_limit: 384m
    memswap_limit: 384m
    mem_reservation: 256m
    cpus: 1
    environment:
      PUID: 4000
      GUID: 4000
      TZ: Europe/Budapest
    volumes:
      - /opt/docker/volumes/adguardhome/conf:/opt/adguardhome/conf
      - /opt/docker/volumes/adguardhome/work:/opt/adguardhome/work
      - /opt/docker/volumes/adguardhome/tailscale/state/certs:/opt/adguardhome/cert
    cap_drop:
      - all
    cap_add:
      - net_bind_service
    security_opt:
      - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "ss -nputwl | grep LISTEN | grep 3000"]
      interval: 1s
      timeout: 5s
      retries: 60
    depends_on:
      tailscale:
        condition: service_healthy
  tailscale:
    image: tailscale/tailscale:latest
    hostname: ${CT_HOSTNAME}
    restart: unless-stopped
    mem_limit: 64m
    memswap_limit: 64m
    mem_reservation: 32m
    cpus: 1
    expose:
       - 53/tcp
       - 53/udp
       - 80/tcp
       - 443/tcp
       - 784/udp
       - 853/tcp
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_SERVE_CONFIG=/config/tailscale.json
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - "/opt/docker/volumes/adguardhome/tailscale/state:/var/lib/tailscale"
      - "/opt/docker/stacks/adguardhome/tailscale.json:/config/tailscale.json:ro"
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - net_admin
      - sys_module
      - net_raw    
    security_opt:
      - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "tailscale status"]
      interval: 1s
      timeout: 5s
      retries: 60