services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    # user: 4000:4000
    mem_limit: 640m
    memswap_limit: 640m
    mem_reservation: 384m
    cpus: 2
    ports:
       - ${BIND_ADDRESS:-127.0.0.1}:53:53/tcp
       - ${BIND_ADDRESS:-127.0.0.1}:53:53/udp
       - ${BIND_ADDRESS:-127.0.0.1}:80:80/tcp
       - ${BIND_ADDRESS:-127.0.0.1}:443:443/tcp
       - ${BIND_ADDRESS:-127.0.0.1}:784:784/udp
       - ${BIND_ADDRESS:-127.0.0.1}:853:853/tcp
    environment:
      PUID: 4000
      GUID: 4000
      TZ: Europe/Budapest
    volumes:
      - /opt/docker/volumes/adguardhome/conf:/opt/adguardhome/conf
      - /opt/docker/volumes/adguardhome/work:/opt/adguardhome/work
      - /opt/docker/volumes/adguardhome/tailscale/state/certs:/opt/adguardhome/cert
    cap_drop:
      - all
    cap_add:
      - net_bind_service
      - net_admin
      - net_raw
      - sys_module
    security_opt:
      - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "wget --spider 127.0.0.1:80"]
      interval: 1s
      timeout: 5s
      retries: 60