services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped
    mem_limit: 384m
    memswap_limit: 384m
    mem_reservation: 128m
    cpus: 2
    ports:
      - 80:8080
    environment:
      - TZ=Europe/Budapest
      - BASE_URL=https://${DOMAIN}
      - INSTANCE_NAME=${INSTANCE_NAME}
    volumes:
      - /opt/docker/volumes/searxng/appdata:/etc/searxng
    security_opt:
      - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "wget --spider 127.0.0.1:8080"]
      interval: 1s
      timeout: 5s
      retries: 60
